### ISSUE TITLE
Node 0.12: Not a valid kExternalUnsignedByteArray

### ISSUE THREAD

**Issue by michaelwittig** [dcodeIO/node-memcpy#4]
Hi,
I get a  TypeError: Illegal source: Not a valid kExternalUnsignedByteArray error when using node 0.12?

````
var memcpy = require("memcpy"); 
var ab = new ArrayBuffer(8);
var buffer = new Buffer(ab.byteLength);
memcpy(buffer, ab);
````

**Comment by mateogianolio** [comment]
No solution to this?

**Comment by michaelwittig** [comment]
I haven't found one. I use Buffers now directly so I just replaced the  
memcp dependency.

Am 15.04.2015 um 19:10 schrieb Mateo Gianolio  
<notifications@github.com>:

**Comment by dcodeIO** [comment]
Currently investigating, but it seems that the version of v8 used in node 0.12 doesn't expose the backing data anymore without externalizing it (which we don't want). There seem to be some workarounds using v8::Utils, but I haven't managed to get it to work, yet, as this is not exposed publicly.

If you have an idea, let me know.
